import type { Context } from '@deepseek-ai/cordis';
import type { DeepCanaryConfigInput } from './config.js';
import { ContextDshAdapter } from './adapters/dsh.js';
import { MetadataStore } from './persistence.js';
import type { CanarySignal, DeepCanaryConfig, InboxItem, PublicInboxItem, PublicSettings, PublicSnapshot, RuntimeStatus } from './types.js';
declare const PLUGIN_NAME = "dsh-deepcanary";
declare const PLUGIN_VERSION = "0.1.0-rc.1";
export declare class DeepCanaryService {
    config: DeepCanaryConfig;
    readonly store: MetadataStore;
    readonly workspace: import("./types.js").WorkspaceIdentity;
    readonly adapter: ContextDshAdapter;
    readonly ready: Promise<void>;
    private readonly ctx;
    private readonly sessions;
    private readonly items;
    private readonly dedupe;
    private readonly budget;
    private readonly pressureSeen;
    private readonly logger;
    private adapterSubscription;
    private activeSubagents;
    private registeredTools;
    private interval;
    private hostProbeInterval;
    private hostProbePort;
    private hostProbeFailures;
    private hostProbeHealthy;
    private settingsScope;
    private settingsSubscription;
    private saveChain;
    private hydrated;
    private disposed;
    private started;
    constructor(ctx: Context, input?: DeepCanaryConfigInput);
    start(): void;
    setRegisteredTools(names: readonly string[]): void;
    ingest(signal: CanarySignal): Promise<InboxItem | undefined>;
    snapshot(): PublicSnapshot;
    status(): RuntimeStatus;
    settings(): PublicSettings;
    updateSettings(input: Record<string, unknown>): Promise<PublicSettings>;
    inbox(limit?: number): PublicInboxItem[];
    acknowledge(id: string): boolean;
    snooze(id: string, minutes?: number): boolean;
    mute(id: string): boolean;
    feedback(id: string, useful: boolean, note?: string): boolean;
    explain(id: string): PublicInboxItem | undefined;
    jump(id: string): {
        sessionId?: string;
        url?: string;
        available: boolean;
        note: string;
    };
    recordHostProbe(ok: boolean, detail?: string): void;
    private probeHost;
    dispose(): Promise<void>;
    private hydrate;
    private onSessionCreated;
    private onSessionDisposed;
    private onSessionEvent;
    private onSubagentDelta;
    private checkStalls;
    private findBundle;
    private mergeBundle;
    private pressureThresholds;
    private applySettings;
    private resetLivenessTimer;
    private resetHostProbeTimer;
    private publicSettings;
    private safeVerdict;
    private isQuietHours;
    private toPublic;
    private isPending;
    private find;
    private queueSave;
}
export { PLUGIN_NAME, PLUGIN_VERSION };
//# sourceMappingURL=service.d.ts.map